// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.API.Models;

#nullable disable

namespace Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240930080102_AddUserDbSet")]
    partial class AddUserDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "4135803517878",
                            CreatedDate = new DateTime(2024, 2, 12, 0, 10, 30, 245, DateTimeKind.Local).AddTicks(792),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Wooden Chair",
                            Price = 369.23094862803396
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8030065369189",
                            CreatedDate = new DateTime(2024, 8, 24, 9, 33, 52, 959, DateTimeKind.Local).AddTicks(7248),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Steel Shoes",
                            Price = 136.24926863901749
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "7003075034317",
                            CreatedDate = new DateTime(2023, 12, 13, 11, 44, 40, 954, DateTimeKind.Local).AddTicks(2203),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handmade Granite Table",
                            Price = 654.6719201783053
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "5416944442618",
                            CreatedDate = new DateTime(2024, 7, 14, 14, 0, 31, 615, DateTimeKind.Local).AddTicks(7116),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handmade Wooden Table",
                            Price = 152.71991566741835
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "6506593104131",
                            CreatedDate = new DateTime(2024, 1, 15, 3, 24, 51, 267, DateTimeKind.Local).AddTicks(8760),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Steel Salad",
                            Price = 746.66057369143732
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "9006862241217",
                            CreatedDate = new DateTime(2024, 7, 29, 4, 3, 39, 591, DateTimeKind.Local).AddTicks(6027),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handcrafted Rubber Bike",
                            Price = 917.39893700526977
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "2881384031594",
                            CreatedDate = new DateTime(2024, 2, 27, 17, 16, 3, 871, DateTimeKind.Local).AddTicks(2233),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Unbranded Steel Car",
                            Price = 805.77746175126049
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "0963435288224",
                            CreatedDate = new DateTime(2024, 5, 22, 14, 4, 25, 717, DateTimeKind.Local).AddTicks(4966),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Tasty Plastic Cheese",
                            Price = 914.85762121428627
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "4771273064520",
                            CreatedDate = new DateTime(2023, 11, 11, 17, 24, 53, 380, DateTimeKind.Local).AddTicks(9739),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Fresh Sausages",
                            Price = 963.08984293839421
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "9845610580792",
                            CreatedDate = new DateTime(2024, 9, 3, 4, 33, 27, 854, DateTimeKind.Local).AddTicks(4612),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantastic Frozen Gloves",
                            Price = 54.201508391742365
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "9878036066984",
                            CreatedDate = new DateTime(2024, 7, 2, 17, 41, 49, 103, DateTimeKind.Local).AddTicks(4145),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Generic Steel Ball",
                            Price = 372.33782553641959
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "5916169237490",
                            CreatedDate = new DateTime(2024, 7, 10, 22, 46, 4, 279, DateTimeKind.Local).AddTicks(4045),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ergonomic Rubber Car",
                            Price = 981.4625697482669
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "0081854460875",
                            CreatedDate = new DateTime(2024, 6, 10, 1, 58, 6, 648, DateTimeKind.Local).AddTicks(965),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Generic Steel Pizza",
                            Price = 318.46874374359322
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "9361989867338",
                            CreatedDate = new DateTime(2023, 12, 5, 2, 51, 13, 515, DateTimeKind.Local).AddTicks(1451),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Metal Sausages",
                            Price = 682.18336528967291
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2406179936436",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 16, 51, 73, DateTimeKind.Local).AddTicks(7117),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantastic Soft Pants",
                            Price = 12.461428898601527
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "5810198703141",
                            CreatedDate = new DateTime(2023, 10, 13, 8, 24, 18, 139, DateTimeKind.Local).AddTicks(1358),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Gorgeous Frozen Towels",
                            Price = 894.2250182457384
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "4328104333418",
                            CreatedDate = new DateTime(2024, 5, 22, 13, 20, 4, 762, DateTimeKind.Local).AddTicks(5030),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Steel Cheese",
                            Price = 715.82718336015341
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "7220837679658",
                            CreatedDate = new DateTime(2024, 5, 19, 14, 51, 12, 865, DateTimeKind.Local).AddTicks(2578),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Gorgeous Granite Cheese",
                            Price = 790.25541884929657
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "7671585538993",
                            CreatedDate = new DateTime(2023, 10, 13, 11, 47, 3, 895, DateTimeKind.Local).AddTicks(4944),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Sleek Rubber Chicken",
                            Price = 121.02393029864129
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "0358152578992",
                            CreatedDate = new DateTime(2024, 3, 5, 22, 46, 9, 869, DateTimeKind.Local).AddTicks(5503),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Intelligent Wooden Salad",
                            Price = 992.13880285766857
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4664420868945",
                            CreatedDate = new DateTime(2024, 5, 14, 14, 43, 9, 466, DateTimeKind.Local).AddTicks(5256),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Wooden Sausages",
                            Price = 43.559941660407901
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "0951801753339",
                            CreatedDate = new DateTime(2023, 12, 26, 0, 57, 27, 194, DateTimeKind.Local).AddTicks(5703),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Sleek Granite Car",
                            Price = 655.64677436353952
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "8592729452441",
                            CreatedDate = new DateTime(2024, 4, 26, 2, 47, 52, 615, DateTimeKind.Local).AddTicks(1682),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Small Wooden Car",
                            Price = 477.23973976924998
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "5286377652096",
                            CreatedDate = new DateTime(2024, 5, 27, 21, 29, 13, 705, DateTimeKind.Local).AddTicks(3868),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Sleek Steel Shirt",
                            Price = 881.80228072814759
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "8812144820985",
                            CreatedDate = new DateTime(2024, 6, 13, 0, 1, 27, 273, DateTimeKind.Local).AddTicks(3151),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Frozen Mouse",
                            Price = 231.27664836648694
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "5122506636813",
                            CreatedDate = new DateTime(2024, 4, 7, 13, 16, 21, 314, DateTimeKind.Local).AddTicks(9878),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Wooden Chair",
                            Price = 481.1636281261051
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "9203244677972",
                            CreatedDate = new DateTime(2023, 12, 28, 18, 43, 28, 313, DateTimeKind.Local).AddTicks(8737),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Gorgeous Plastic Chips",
                            Price = 603.96496611319719
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "7631650700663",
                            CreatedDate = new DateTime(2024, 3, 22, 2, 41, 11, 247, DateTimeKind.Local).AddTicks(6214),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Fresh Bacon",
                            Price = 639.02985308320717
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "0198782966956",
                            CreatedDate = new DateTime(2024, 6, 14, 18, 45, 12, 785, DateTimeKind.Local).AddTicks(9379),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Soft Computer",
                            Price = 68.019930013930392
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "7865344300260",
                            CreatedDate = new DateTime(2023, 10, 10, 3, 22, 20, 449, DateTimeKind.Local).AddTicks(2836),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Rubber Bike",
                            Price = 193.52063540160685
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "0984868484793",
                            CreatedDate = new DateTime(2024, 9, 4, 23, 29, 49, 232, DateTimeKind.Local).AddTicks(9391),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Handcrafted Concrete Tuna",
                            Price = 702.7774551775201
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "5585438269625",
                            CreatedDate = new DateTime(2024, 6, 15, 13, 56, 59, 955, DateTimeKind.Local).AddTicks(3762),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Wooden Fish",
                            Price = 313.11708069225637
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "1399786951996",
                            CreatedDate = new DateTime(2024, 3, 23, 8, 54, 42, 140, DateTimeKind.Local).AddTicks(8970),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handcrafted Frozen Keyboard",
                            Price = 174.63402698684206
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "6545660875116",
                            CreatedDate = new DateTime(2023, 10, 20, 16, 1, 49, 836, DateTimeKind.Local).AddTicks(7484),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Intelligent Plastic Chair",
                            Price = 98.709883321407204
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "2579847727442",
                            CreatedDate = new DateTime(2023, 11, 7, 22, 5, 56, 702, DateTimeKind.Local).AddTicks(9369),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Unbranded Wooden Pizza",
                            Price = 614.77223599179285
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "7673981084104",
                            CreatedDate = new DateTime(2023, 11, 27, 17, 57, 54, 886, DateTimeKind.Local).AddTicks(8920),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Gorgeous Rubber Bacon",
                            Price = 467.51950786193811
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "3770783333684",
                            CreatedDate = new DateTime(2024, 2, 23, 15, 16, 55, 661, DateTimeKind.Local).AddTicks(8751),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handcrafted Rubber Shirt",
                            Price = 759.76310902077853
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "2869876351887",
                            CreatedDate = new DateTime(2023, 12, 5, 8, 2, 39, 543, DateTimeKind.Local).AddTicks(5299),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Granite Shoes",
                            Price = 82.488060594763638
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "9788064749806",
                            CreatedDate = new DateTime(2024, 2, 29, 21, 21, 26, 690, DateTimeKind.Local).AddTicks(8784),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Sleek Granite Chair",
                            Price = 403.20283056246245
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "8499343245513",
                            CreatedDate = new DateTime(2024, 5, 18, 23, 18, 51, 743, DateTimeKind.Local).AddTicks(7606),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Incredible Rubber Soap",
                            Price = 143.57838060640654
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "1489403745555",
                            CreatedDate = new DateTime(2024, 7, 1, 9, 15, 2, 445, DateTimeKind.Local).AddTicks(7956),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Awesome Soft Fish",
                            Price = 589.62004119838593
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8933482922527",
                            CreatedDate = new DateTime(2024, 6, 22, 19, 52, 21, 764, DateTimeKind.Local).AddTicks(1764),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Intelligent Cotton Tuna",
                            Price = 145.62097877432637
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "0809669868323",
                            CreatedDate = new DateTime(2023, 12, 15, 23, 11, 35, 521, DateTimeKind.Local).AddTicks(5966),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Refined Soft Bike",
                            Price = 422.75872662419391
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "9790757012272",
                            CreatedDate = new DateTime(2023, 12, 19, 21, 7, 24, 584, DateTimeKind.Local).AddTicks(9034),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handmade Cotton Bacon",
                            Price = 925.07466158181182
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "9836461369483",
                            CreatedDate = new DateTime(2023, 11, 27, 15, 46, 21, 581, DateTimeKind.Local).AddTicks(2742),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Small Soft Tuna",
                            Price = 613.52794189542897
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "8915255768136",
                            CreatedDate = new DateTime(2024, 4, 1, 4, 42, 28, 569, DateTimeKind.Local).AddTicks(5539),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Frozen Computer",
                            Price = 280.04287884945182
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "2233848753373",
                            CreatedDate = new DateTime(2023, 12, 5, 15, 59, 38, 143, DateTimeKind.Local).AddTicks(9285),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Wooden Mouse",
                            Price = 883.87747143203273
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "1467160313439",
                            CreatedDate = new DateTime(2024, 1, 17, 15, 41, 3, 343, DateTimeKind.Local).AddTicks(6614),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handcrafted Metal Mouse",
                            Price = 828.79833626691175
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "2506649138046",
                            CreatedDate = new DateTime(2024, 3, 1, 23, 17, 28, 654, DateTimeKind.Local).AddTicks(824),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Rubber Salad",
                            Price = 840.99831578927035
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "3416252522677",
                            CreatedDate = new DateTime(2024, 7, 19, 21, 37, 0, 544, DateTimeKind.Local).AddTicks(323),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incredible Plastic Shoes",
                            Price = 36.028621714575507
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "5582893227719",
                            CreatedDate = new DateTime(2023, 10, 5, 2, 20, 10, 793, DateTimeKind.Local).AddTicks(2674),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Unbranded Soft Fish",
                            Price = 903.58063168198828
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "8524302656618",
                            CreatedDate = new DateTime(2024, 2, 6, 7, 24, 31, 986, DateTimeKind.Local).AddTicks(2836),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Gorgeous Rubber Computer",
                            Price = 540.61067063902078
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "6161303580232",
                            CreatedDate = new DateTime(2024, 8, 30, 2, 24, 31, 795, DateTimeKind.Local).AddTicks(3589),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Refined Cotton Chair",
                            Price = 861.54531531946054
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "1118914751082",
                            CreatedDate = new DateTime(2024, 1, 4, 13, 58, 34, 688, DateTimeKind.Local).AddTicks(3577),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomic Cotton Shoes",
                            Price = 828.60533404471596
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "6721181141552",
                            CreatedDate = new DateTime(2024, 1, 6, 6, 2, 44, 585, DateTimeKind.Local).AddTicks(5504),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Tasty Cotton Computer",
                            Price = 481.52617973299988
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "3815754149328",
                            CreatedDate = new DateTime(2024, 9, 28, 22, 3, 8, 323, DateTimeKind.Local).AddTicks(8840),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Intelligent Steel Computer",
                            Price = 899.10140674240017
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "0993677210387",
                            CreatedDate = new DateTime(2023, 11, 26, 16, 32, 58, 946, DateTimeKind.Local).AddTicks(7547),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Tasty Rubber Chips",
                            Price = 778.88751567056761
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "2106693181151",
                            CreatedDate = new DateTime(2023, 10, 18, 14, 40, 34, 874, DateTimeKind.Local).AddTicks(5843),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Generic Steel Tuna",
                            Price = 711.08651894381569
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "8013854475179",
                            CreatedDate = new DateTime(2024, 7, 15, 8, 13, 59, 649, DateTimeKind.Local).AddTicks(9563),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Cotton Chips",
                            Price = 99.117536574656867
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "0329049506060",
                            CreatedDate = new DateTime(2024, 4, 2, 14, 16, 23, 708, DateTimeKind.Local).AddTicks(8142),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Fantastic Plastic Sausages",
                            Price = 744.52879473079406
                        },
                        new
                        {
                            Id = 61,
                            Barcode = "4835221701988",
                            CreatedDate = new DateTime(2024, 6, 19, 18, 23, 7, 693, DateTimeKind.Local).AddTicks(7048),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Unbranded Granite Keyboard",
                            Price = 814.83999403465532
                        },
                        new
                        {
                            Id = 62,
                            Barcode = "6807424731022",
                            CreatedDate = new DateTime(2024, 7, 20, 7, 21, 42, 488, DateTimeKind.Local).AddTicks(2642),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Steel Cheese",
                            Price = 910.83703496858334
                        },
                        new
                        {
                            Id = 63,
                            Barcode = "2500724862307",
                            CreatedDate = new DateTime(2024, 2, 6, 19, 56, 43, 981, DateTimeKind.Local).AddTicks(2569),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Rubber Soap",
                            Price = 494.04385483918895
                        },
                        new
                        {
                            Id = 64,
                            Barcode = "6741048067986",
                            CreatedDate = new DateTime(2024, 7, 4, 8, 0, 6, 96, DateTimeKind.Local).AddTicks(9417),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Frozen Cheese",
                            Price = 472.22565057604834
                        },
                        new
                        {
                            Id = 65,
                            Barcode = "7507355242534",
                            CreatedDate = new DateTime(2024, 6, 21, 2, 16, 38, 215, DateTimeKind.Local).AddTicks(5131),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Granite Keyboard",
                            Price = 488.74166859907177
                        },
                        new
                        {
                            Id = 66,
                            Barcode = "4145275688969",
                            CreatedDate = new DateTime(2024, 3, 4, 8, 24, 0, 878, DateTimeKind.Local).AddTicks(8670),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Practical Rubber Soap",
                            Price = 974.50585199683246
                        },
                        new
                        {
                            Id = 67,
                            Barcode = "9848580553544",
                            CreatedDate = new DateTime(2024, 7, 8, 2, 28, 21, 214, DateTimeKind.Local).AddTicks(5234),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Sleek Concrete Soap",
                            Price = 54.502270389582158
                        },
                        new
                        {
                            Id = 68,
                            Barcode = "8132167627799",
                            CreatedDate = new DateTime(2024, 8, 11, 7, 43, 0, 507, DateTimeKind.Local).AddTicks(237),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Generic Metal Fish",
                            Price = 712.63407267333662
                        },
                        new
                        {
                            Id = 69,
                            Barcode = "3556572214637",
                            CreatedDate = new DateTime(2023, 10, 10, 12, 36, 17, 604, DateTimeKind.Local).AddTicks(5900),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Cotton Fish",
                            Price = 684.43849226619977
                        },
                        new
                        {
                            Id = 70,
                            Barcode = "5667185285186",
                            CreatedDate = new DateTime(2024, 8, 24, 21, 20, 46, 55, DateTimeKind.Local).AddTicks(7279),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Refined Soft Salad",
                            Price = 716.42358648237939
                        },
                        new
                        {
                            Id = 71,
                            Barcode = "7155095308883",
                            CreatedDate = new DateTime(2024, 7, 25, 15, 36, 51, 377, DateTimeKind.Local).AddTicks(597),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Sleek Frozen Towels",
                            Price = 382.32254860378919
                        },
                        new
                        {
                            Id = 72,
                            Barcode = "4646139602317",
                            CreatedDate = new DateTime(2024, 5, 11, 4, 23, 24, 936, DateTimeKind.Local).AddTicks(8262),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Frozen Table",
                            Price = 142.4809324873988
                        },
                        new
                        {
                            Id = 73,
                            Barcode = "4957188649391",
                            CreatedDate = new DateTime(2023, 11, 14, 4, 7, 8, 513, DateTimeKind.Local).AddTicks(1169),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Fantastic Cotton Tuna",
                            Price = 204.71544998731252
                        },
                        new
                        {
                            Id = 74,
                            Barcode = "7001638309445",
                            CreatedDate = new DateTime(2024, 4, 23, 17, 39, 41, 848, DateTimeKind.Local).AddTicks(7424),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Cotton Salad",
                            Price = 124.32340843059281
                        },
                        new
                        {
                            Id = 75,
                            Barcode = "5755849031368",
                            CreatedDate = new DateTime(2024, 1, 7, 17, 18, 5, 319, DateTimeKind.Local).AddTicks(8291),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Awesome Steel Table",
                            Price = 42.994053510480583
                        },
                        new
                        {
                            Id = 76,
                            Barcode = "4231878819487",
                            CreatedDate = new DateTime(2023, 10, 22, 8, 30, 42, 427, DateTimeKind.Local).AddTicks(3216),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Sleek Concrete Fish",
                            Price = 909.74176722147592
                        },
                        new
                        {
                            Id = 77,
                            Barcode = "2116260793298",
                            CreatedDate = new DateTime(2024, 8, 4, 2, 10, 54, 423, DateTimeKind.Local).AddTicks(7401),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Practical Rubber Bike",
                            Price = 364.24190835852266
                        },
                        new
                        {
                            Id = 78,
                            Barcode = "8387792955193",
                            CreatedDate = new DateTime(2024, 9, 16, 20, 7, 32, 15, DateTimeKind.Local).AddTicks(8992),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Rubber Bacon",
                            Price = 17.030882716658933
                        },
                        new
                        {
                            Id = 79,
                            Barcode = "0796118461870",
                            CreatedDate = new DateTime(2024, 7, 16, 13, 6, 48, 914, DateTimeKind.Local).AddTicks(5085),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Sleek Wooden Salad",
                            Price = 500.19197839181498
                        },
                        new
                        {
                            Id = 80,
                            Barcode = "5441420559375",
                            CreatedDate = new DateTime(2023, 11, 19, 22, 31, 36, 193, DateTimeKind.Local).AddTicks(3645),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ergonomic Cotton Cheese",
                            Price = 388.41101128254599
                        },
                        new
                        {
                            Id = 81,
                            Barcode = "8127822017206",
                            CreatedDate = new DateTime(2024, 3, 18, 20, 42, 48, 985, DateTimeKind.Local).AddTicks(5578),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Gorgeous Concrete Salad",
                            Price = 790.18422065870107
                        },
                        new
                        {
                            Id = 82,
                            Barcode = "2836556819357",
                            CreatedDate = new DateTime(2024, 3, 19, 7, 42, 30, 518, DateTimeKind.Local).AddTicks(6241),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Gorgeous Wooden Keyboard",
                            Price = 359.85921197657439
                        },
                        new
                        {
                            Id = 83,
                            Barcode = "7852841324400",
                            CreatedDate = new DateTime(2024, 2, 27, 18, 3, 8, 262, DateTimeKind.Local).AddTicks(9561),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Plastic Keyboard",
                            Price = 918.91680194992421
                        },
                        new
                        {
                            Id = 84,
                            Barcode = "9256100365292",
                            CreatedDate = new DateTime(2023, 12, 31, 6, 7, 44, 863, DateTimeKind.Local).AddTicks(8130),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Frozen Mouse",
                            Price = 609.57094184428968
                        },
                        new
                        {
                            Id = 85,
                            Barcode = "4098423130363",
                            CreatedDate = new DateTime(2024, 2, 11, 2, 35, 56, 160, DateTimeKind.Local).AddTicks(2625),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Fantastic Plastic Pizza",
                            Price = 346.4543799690224
                        },
                        new
                        {
                            Id = 86,
                            Barcode = "7165157502708",
                            CreatedDate = new DateTime(2024, 1, 6, 12, 21, 35, 411, DateTimeKind.Local).AddTicks(851),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Incredible Metal Shirt",
                            Price = 219.69463843558665
                        },
                        new
                        {
                            Id = 87,
                            Barcode = "9072296990991",
                            CreatedDate = new DateTime(2024, 6, 24, 1, 33, 53, 667, DateTimeKind.Local).AddTicks(6440),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handmade Cotton Pants",
                            Price = 771.37464212690236
                        },
                        new
                        {
                            Id = 88,
                            Barcode = "8893182042362",
                            CreatedDate = new DateTime(2024, 7, 15, 4, 42, 35, 252, DateTimeKind.Local).AddTicks(9546),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Fantastic Wooden Soap",
                            Price = 168.63343464472959
                        },
                        new
                        {
                            Id = 89,
                            Barcode = "0487815661938",
                            CreatedDate = new DateTime(2023, 10, 25, 5, 20, 13, 894, DateTimeKind.Local).AddTicks(9022),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Rubber Mouse",
                            Price = 383.80313230576138
                        },
                        new
                        {
                            Id = 90,
                            Barcode = "5688025363864",
                            CreatedDate = new DateTime(2024, 5, 19, 21, 38, 9, 637, DateTimeKind.Local).AddTicks(8699),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Rubber Mouse",
                            Price = 487.67439399877298
                        },
                        new
                        {
                            Id = 91,
                            Barcode = "3107752100327",
                            CreatedDate = new DateTime(2024, 8, 22, 12, 12, 26, 439, DateTimeKind.Local).AddTicks(2674),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonomic Frozen Chips",
                            Price = 605.73248992056233
                        },
                        new
                        {
                            Id = 92,
                            Barcode = "3146155279780",
                            CreatedDate = new DateTime(2024, 5, 22, 21, 3, 47, 783, DateTimeKind.Local).AddTicks(1568),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Soft Chicken",
                            Price = 572.13452711335128
                        },
                        new
                        {
                            Id = 93,
                            Barcode = "8883591493282",
                            CreatedDate = new DateTime(2023, 11, 15, 18, 34, 44, 52, DateTimeKind.Local).AddTicks(9101),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Tasty Granite Pizza",
                            Price = 835.07818786943244
                        },
                        new
                        {
                            Id = 94,
                            Barcode = "2794257231741",
                            CreatedDate = new DateTime(2024, 1, 4, 16, 16, 29, 586, DateTimeKind.Local).AddTicks(2920),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Granite Bike",
                            Price = 669.1514615426546
                        },
                        new
                        {
                            Id = 95,
                            Barcode = "9965575108104",
                            CreatedDate = new DateTime(2024, 5, 17, 22, 43, 23, 148, DateTimeKind.Local).AddTicks(6665),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Concrete Table",
                            Price = 808.69116524545996
                        },
                        new
                        {
                            Id = 96,
                            Barcode = "3352535975696",
                            CreatedDate = new DateTime(2024, 1, 30, 9, 7, 34, 586, DateTimeKind.Local).AddTicks(1442),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Rustic Plastic Computer",
                            Price = 561.68517456282166
                        },
                        new
                        {
                            Id = 97,
                            Barcode = "7711914812858",
                            CreatedDate = new DateTime(2024, 8, 15, 0, 52, 25, 275, DateTimeKind.Local).AddTicks(2231),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Practical Fresh Cheese",
                            Price = 239.76816976571837
                        },
                        new
                        {
                            Id = 98,
                            Barcode = "2642950951261",
                            CreatedDate = new DateTime(2024, 7, 19, 11, 7, 5, 16, DateTimeKind.Local).AddTicks(6664),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Generic Metal Car",
                            Price = 59.559374826755082
                        },
                        new
                        {
                            Id = 99,
                            Barcode = "9133862211404",
                            CreatedDate = new DateTime(2024, 7, 10, 5, 57, 23, 831, DateTimeKind.Local).AddTicks(6284),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Generic Fresh Soap",
                            Price = 323.8241613888294
                        },
                        new
                        {
                            Id = 100,
                            Barcode = "2476106364021",
                            CreatedDate = new DateTime(2024, 1, 25, 18, 53, 5, 952, DateTimeKind.Local).AddTicks(8538),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Generic Cotton Table",
                            Price = 508.81764639300189
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
