// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.API.Models;

#nullable disable

namespace Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240923083604_AddInitialData")]
    partial class AddInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "4135803517878",
                            CreatedDate = new DateTime(2024, 2, 5, 0, 45, 36, 16, DateTimeKind.Local).AddTicks(8669),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Wooden Chair",
                            Price = 369.23094862803396
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8030065369189",
                            CreatedDate = new DateTime(2024, 8, 17, 10, 8, 58, 731, DateTimeKind.Local).AddTicks(5061),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Steel Shoes",
                            Price = 136.24926863901749
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "7003075034317",
                            CreatedDate = new DateTime(2023, 12, 6, 12, 19, 46, 726, DateTimeKind.Local).AddTicks(9),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handmade Granite Table",
                            Price = 654.6719201783053
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "5416944442618",
                            CreatedDate = new DateTime(2024, 7, 7, 14, 35, 37, 387, DateTimeKind.Local).AddTicks(4946),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handmade Wooden Table",
                            Price = 152.71991566741835
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "6506593104131",
                            CreatedDate = new DateTime(2024, 1, 8, 3, 59, 57, 39, DateTimeKind.Local).AddTicks(6582),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Steel Salad",
                            Price = 746.66057369143732
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "9006862241217",
                            CreatedDate = new DateTime(2024, 7, 22, 4, 38, 45, 363, DateTimeKind.Local).AddTicks(3935),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handcrafted Rubber Bike",
                            Price = 917.39893700526977
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "2881384031594",
                            CreatedDate = new DateTime(2024, 2, 20, 17, 51, 9, 643, DateTimeKind.Local).AddTicks(170),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Unbranded Steel Car",
                            Price = 805.77746175126049
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "0963435288224",
                            CreatedDate = new DateTime(2024, 5, 15, 14, 39, 31, 489, DateTimeKind.Local).AddTicks(2883),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Tasty Plastic Cheese",
                            Price = 914.85762121428627
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "4771273064520",
                            CreatedDate = new DateTime(2023, 11, 4, 17, 59, 59, 152, DateTimeKind.Local).AddTicks(7651),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Fresh Sausages",
                            Price = 963.08984293839421
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "9845610580792",
                            CreatedDate = new DateTime(2024, 8, 27, 5, 8, 33, 626, DateTimeKind.Local).AddTicks(2523),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantastic Frozen Gloves",
                            Price = 54.201508391742365
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "9878036066984",
                            CreatedDate = new DateTime(2024, 6, 25, 18, 16, 54, 875, DateTimeKind.Local).AddTicks(2081),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Generic Steel Ball",
                            Price = 372.33782553641959
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "5916169237490",
                            CreatedDate = new DateTime(2024, 7, 3, 23, 21, 10, 51, DateTimeKind.Local).AddTicks(1976),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ergonomic Rubber Car",
                            Price = 981.4625697482669
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "0081854460875",
                            CreatedDate = new DateTime(2024, 6, 3, 2, 33, 12, 419, DateTimeKind.Local).AddTicks(8891),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Generic Steel Pizza",
                            Price = 318.46874374359322
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "9361989867338",
                            CreatedDate = new DateTime(2023, 11, 28, 3, 26, 19, 286, DateTimeKind.Local).AddTicks(9372),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Metal Sausages",
                            Price = 682.18336528967291
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2406179936436",
                            CreatedDate = new DateTime(2024, 6, 18, 9, 51, 56, 845, DateTimeKind.Local).AddTicks(4992),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantastic Soft Pants",
                            Price = 12.461428898601527
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "5810198703141",
                            CreatedDate = new DateTime(2023, 10, 6, 8, 59, 23, 910, DateTimeKind.Local).AddTicks(9226),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Gorgeous Frozen Towels",
                            Price = 894.2250182457384
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "4328104333418",
                            CreatedDate = new DateTime(2024, 5, 15, 13, 55, 10, 534, DateTimeKind.Local).AddTicks(2892),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Steel Cheese",
                            Price = 715.82718336015341
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "7220837679658",
                            CreatedDate = new DateTime(2024, 5, 12, 15, 26, 18, 637, DateTimeKind.Local).AddTicks(451),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Gorgeous Granite Cheese",
                            Price = 790.25541884929657
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "7671585538993",
                            CreatedDate = new DateTime(2023, 10, 6, 12, 22, 9, 667, DateTimeKind.Local).AddTicks(2813),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Sleek Rubber Chicken",
                            Price = 121.02393029864129
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "0358152578992",
                            CreatedDate = new DateTime(2024, 2, 27, 23, 21, 15, 641, DateTimeKind.Local).AddTicks(3368),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Intelligent Wooden Salad",
                            Price = 992.13880285766857
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4664420868945",
                            CreatedDate = new DateTime(2024, 5, 7, 15, 18, 15, 238, DateTimeKind.Local).AddTicks(3083),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Wooden Sausages",
                            Price = 43.559941660407901
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "0951801753339",
                            CreatedDate = new DateTime(2023, 12, 19, 1, 32, 32, 966, DateTimeKind.Local).AddTicks(3523),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Sleek Granite Car",
                            Price = 655.64677436353952
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "8592729452441",
                            CreatedDate = new DateTime(2024, 4, 19, 3, 22, 58, 386, DateTimeKind.Local).AddTicks(9498),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Small Wooden Car",
                            Price = 477.23973976924998
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "5286377652096",
                            CreatedDate = new DateTime(2024, 5, 20, 22, 4, 19, 477, DateTimeKind.Local).AddTicks(1677),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Sleek Steel Shirt",
                            Price = 881.80228072814759
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "8812144820985",
                            CreatedDate = new DateTime(2024, 6, 6, 0, 36, 33, 45, DateTimeKind.Local).AddTicks(1000),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Frozen Mouse",
                            Price = 231.27664836648694
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "5122506636813",
                            CreatedDate = new DateTime(2024, 3, 31, 13, 51, 27, 86, DateTimeKind.Local).AddTicks(7724),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Wooden Chair",
                            Price = 481.1636281261051
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "9203244677972",
                            CreatedDate = new DateTime(2023, 12, 21, 19, 18, 34, 85, DateTimeKind.Local).AddTicks(6575),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Gorgeous Plastic Chips",
                            Price = 603.96496611319719
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "7631650700663",
                            CreatedDate = new DateTime(2024, 3, 15, 3, 16, 17, 19, DateTimeKind.Local).AddTicks(4020),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Fresh Bacon",
                            Price = 639.02985308320717
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "0198782966956",
                            CreatedDate = new DateTime(2024, 6, 7, 19, 20, 18, 557, DateTimeKind.Local).AddTicks(7182),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Soft Computer",
                            Price = 68.019930013930392
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "7865344300260",
                            CreatedDate = new DateTime(2023, 10, 3, 3, 57, 26, 221, DateTimeKind.Local).AddTicks(635),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Rubber Bike",
                            Price = 193.52063540160685
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "0984868484793",
                            CreatedDate = new DateTime(2024, 8, 29, 0, 4, 55, 4, DateTimeKind.Local).AddTicks(7226),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Handcrafted Concrete Tuna",
                            Price = 702.7774551775201
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "5585438269625",
                            CreatedDate = new DateTime(2024, 6, 8, 14, 32, 5, 727, DateTimeKind.Local).AddTicks(1595),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Wooden Fish",
                            Price = 313.11708069225637
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "1399786951996",
                            CreatedDate = new DateTime(2024, 3, 16, 9, 29, 47, 912, DateTimeKind.Local).AddTicks(6800),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handcrafted Frozen Keyboard",
                            Price = 174.63402698684206
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "6545660875116",
                            CreatedDate = new DateTime(2023, 10, 13, 16, 36, 55, 608, DateTimeKind.Local).AddTicks(5311),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Intelligent Plastic Chair",
                            Price = 98.709883321407204
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "2579847727442",
                            CreatedDate = new DateTime(2023, 10, 31, 22, 41, 2, 474, DateTimeKind.Local).AddTicks(7167),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Unbranded Wooden Pizza",
                            Price = 614.77223599179285
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "7673981084104",
                            CreatedDate = new DateTime(2023, 11, 20, 18, 33, 0, 658, DateTimeKind.Local).AddTicks(6711),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Gorgeous Rubber Bacon",
                            Price = 467.51950786193811
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "3770783333684",
                            CreatedDate = new DateTime(2024, 2, 16, 15, 52, 1, 433, DateTimeKind.Local).AddTicks(6529),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handcrafted Rubber Shirt",
                            Price = 759.76310902077853
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "2869876351887",
                            CreatedDate = new DateTime(2023, 11, 28, 8, 37, 45, 315, DateTimeKind.Local).AddTicks(3101),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Granite Shoes",
                            Price = 82.488060594763638
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "9788064749806",
                            CreatedDate = new DateTime(2024, 2, 22, 21, 56, 32, 462, DateTimeKind.Local).AddTicks(6584),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Sleek Granite Chair",
                            Price = 403.20283056246245
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "8499343245513",
                            CreatedDate = new DateTime(2024, 5, 11, 23, 53, 57, 515, DateTimeKind.Local).AddTicks(5405),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Incredible Rubber Soap",
                            Price = 143.57838060640654
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "1489403745555",
                            CreatedDate = new DateTime(2024, 6, 24, 9, 50, 8, 217, DateTimeKind.Local).AddTicks(5750),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Awesome Soft Fish",
                            Price = 589.62004119838593
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8933482922527",
                            CreatedDate = new DateTime(2024, 6, 15, 20, 27, 27, 535, DateTimeKind.Local).AddTicks(9533),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Intelligent Cotton Tuna",
                            Price = 145.62097877432637
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "0809669868323",
                            CreatedDate = new DateTime(2023, 12, 8, 23, 46, 41, 293, DateTimeKind.Local).AddTicks(3731),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Refined Soft Bike",
                            Price = 422.75872662419391
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "9790757012272",
                            CreatedDate = new DateTime(2023, 12, 12, 21, 42, 30, 356, DateTimeKind.Local).AddTicks(6794),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handmade Cotton Bacon",
                            Price = 925.07466158181182
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "9836461369483",
                            CreatedDate = new DateTime(2023, 11, 20, 16, 21, 27, 353, DateTimeKind.Local).AddTicks(529),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Small Soft Tuna",
                            Price = 613.52794189542897
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "8915255768136",
                            CreatedDate = new DateTime(2024, 3, 25, 5, 17, 34, 341, DateTimeKind.Local).AddTicks(3327),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Frozen Computer",
                            Price = 280.04287884945182
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "2233848753373",
                            CreatedDate = new DateTime(2023, 11, 28, 16, 34, 43, 915, DateTimeKind.Local).AddTicks(7092),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Wooden Mouse",
                            Price = 883.87747143203273
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "1467160313439",
                            CreatedDate = new DateTime(2024, 1, 10, 16, 16, 9, 115, DateTimeKind.Local).AddTicks(4431),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handcrafted Metal Mouse",
                            Price = 828.79833626691175
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "2506649138046",
                            CreatedDate = new DateTime(2024, 2, 23, 23, 52, 34, 425, DateTimeKind.Local).AddTicks(8628),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Handcrafted Rubber Salad",
                            Price = 840.99831578927035
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "3416252522677",
                            CreatedDate = new DateTime(2024, 7, 12, 22, 12, 6, 315, DateTimeKind.Local).AddTicks(8129),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incredible Plastic Shoes",
                            Price = 36.028621714575507
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "5582893227719",
                            CreatedDate = new DateTime(2023, 9, 28, 2, 55, 16, 565, DateTimeKind.Local).AddTicks(492),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Unbranded Soft Fish",
                            Price = 903.58063168198828
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "8524302656618",
                            CreatedDate = new DateTime(2024, 1, 30, 7, 59, 37, 758, DateTimeKind.Local).AddTicks(694),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Gorgeous Rubber Computer",
                            Price = 540.61067063902078
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "6161303580232",
                            CreatedDate = new DateTime(2024, 8, 23, 2, 59, 37, 567, DateTimeKind.Local).AddTicks(1446),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Refined Cotton Chair",
                            Price = 861.54531531946054
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "1118914751082",
                            CreatedDate = new DateTime(2023, 12, 28, 14, 33, 40, 460, DateTimeKind.Local).AddTicks(1431),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomic Cotton Shoes",
                            Price = 828.60533404471596
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "6721181141552",
                            CreatedDate = new DateTime(2023, 12, 30, 6, 37, 50, 357, DateTimeKind.Local).AddTicks(3361),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Tasty Cotton Computer",
                            Price = 481.52617973299988
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "3815754149328",
                            CreatedDate = new DateTime(2024, 9, 21, 22, 38, 14, 95, DateTimeKind.Local).AddTicks(6670),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Intelligent Steel Computer",
                            Price = 899.10140674240017
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "0993677210387",
                            CreatedDate = new DateTime(2023, 11, 19, 17, 8, 4, 718, DateTimeKind.Local).AddTicks(5375),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Tasty Rubber Chips",
                            Price = 778.88751567056761
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "2106693181151",
                            CreatedDate = new DateTime(2023, 10, 11, 15, 15, 40, 646, DateTimeKind.Local).AddTicks(3669),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Generic Steel Tuna",
                            Price = 711.08651894381569
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "8013854475179",
                            CreatedDate = new DateTime(2024, 7, 8, 8, 49, 5, 421, DateTimeKind.Local).AddTicks(7419),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Cotton Chips",
                            Price = 99.117536574656867
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "0329049506060",
                            CreatedDate = new DateTime(2024, 3, 26, 14, 51, 29, 480, DateTimeKind.Local).AddTicks(5999),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Fantastic Plastic Sausages",
                            Price = 744.52879473079406
                        },
                        new
                        {
                            Id = 61,
                            Barcode = "4835221701988",
                            CreatedDate = new DateTime(2024, 6, 12, 18, 58, 13, 465, DateTimeKind.Local).AddTicks(4903),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Unbranded Granite Keyboard",
                            Price = 814.83999403465532
                        },
                        new
                        {
                            Id = 62,
                            Barcode = "6807424731022",
                            CreatedDate = new DateTime(2024, 7, 13, 7, 56, 48, 260, DateTimeKind.Local).AddTicks(496),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Steel Cheese",
                            Price = 910.83703496858334
                        },
                        new
                        {
                            Id = 63,
                            Barcode = "2500724862307",
                            CreatedDate = new DateTime(2024, 1, 30, 20, 31, 49, 753, DateTimeKind.Local).AddTicks(406),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Rubber Soap",
                            Price = 494.04385483918895
                        },
                        new
                        {
                            Id = 64,
                            Barcode = "6741048067986",
                            CreatedDate = new DateTime(2024, 6, 27, 8, 35, 11, 868, DateTimeKind.Local).AddTicks(7251),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Frozen Cheese",
                            Price = 472.22565057604834
                        },
                        new
                        {
                            Id = 65,
                            Barcode = "7507355242534",
                            CreatedDate = new DateTime(2024, 6, 14, 2, 51, 43, 987, DateTimeKind.Local).AddTicks(2964),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Granite Keyboard",
                            Price = 488.74166859907177
                        },
                        new
                        {
                            Id = 66,
                            Barcode = "4145275688969",
                            CreatedDate = new DateTime(2024, 2, 26, 8, 59, 6, 650, DateTimeKind.Local).AddTicks(6542),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Practical Rubber Soap",
                            Price = 974.50585199683246
                        },
                        new
                        {
                            Id = 67,
                            Barcode = "9848580553544",
                            CreatedDate = new DateTime(2024, 7, 1, 3, 3, 26, 986, DateTimeKind.Local).AddTicks(3105),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Sleek Concrete Soap",
                            Price = 54.502270389582158
                        },
                        new
                        {
                            Id = 68,
                            Barcode = "8132167627799",
                            CreatedDate = new DateTime(2024, 8, 4, 8, 18, 6, 278, DateTimeKind.Local).AddTicks(8105),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Generic Metal Fish",
                            Price = 712.63407267333662
                        },
                        new
                        {
                            Id = 69,
                            Barcode = "3556572214637",
                            CreatedDate = new DateTime(2023, 10, 3, 13, 11, 23, 376, DateTimeKind.Local).AddTicks(3737),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Cotton Fish",
                            Price = 684.43849226619977
                        },
                        new
                        {
                            Id = 70,
                            Barcode = "5667185285186",
                            CreatedDate = new DateTime(2024, 8, 17, 21, 55, 51, 827, DateTimeKind.Local).AddTicks(5114),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Refined Soft Salad",
                            Price = 716.42358648237939
                        },
                        new
                        {
                            Id = 71,
                            Barcode = "7155095308883",
                            CreatedDate = new DateTime(2024, 7, 18, 16, 11, 57, 148, DateTimeKind.Local).AddTicks(8432),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Sleek Frozen Towels",
                            Price = 382.32254860378919
                        },
                        new
                        {
                            Id = 72,
                            Barcode = "4646139602317",
                            CreatedDate = new DateTime(2024, 5, 4, 4, 58, 30, 708, DateTimeKind.Local).AddTicks(6133),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Frozen Table",
                            Price = 142.4809324873988
                        },
                        new
                        {
                            Id = 73,
                            Barcode = "4957188649391",
                            CreatedDate = new DateTime(2023, 11, 7, 4, 42, 14, 284, DateTimeKind.Local).AddTicks(9043),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Fantastic Cotton Tuna",
                            Price = 204.71544998731252
                        },
                        new
                        {
                            Id = 74,
                            Barcode = "7001638309445",
                            CreatedDate = new DateTime(2024, 4, 16, 18, 14, 47, 620, DateTimeKind.Local).AddTicks(5299),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Cotton Salad",
                            Price = 124.32340843059281
                        },
                        new
                        {
                            Id = 75,
                            Barcode = "5755849031368",
                            CreatedDate = new DateTime(2023, 12, 31, 17, 53, 11, 91, DateTimeKind.Local).AddTicks(6167),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Awesome Steel Table",
                            Price = 42.994053510480583
                        },
                        new
                        {
                            Id = 76,
                            Barcode = "4231878819487",
                            CreatedDate = new DateTime(2023, 10, 15, 9, 5, 48, 199, DateTimeKind.Local).AddTicks(1059),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Sleek Concrete Fish",
                            Price = 909.74176722147592
                        },
                        new
                        {
                            Id = 77,
                            Barcode = "2116260793298",
                            CreatedDate = new DateTime(2024, 7, 28, 2, 46, 0, 195, DateTimeKind.Local).AddTicks(5241),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Practical Rubber Bike",
                            Price = 364.24190835852266
                        },
                        new
                        {
                            Id = 78,
                            Barcode = "8387792955193",
                            CreatedDate = new DateTime(2024, 9, 9, 20, 42, 37, 787, DateTimeKind.Local).AddTicks(6832),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Rubber Bacon",
                            Price = 17.030882716658933
                        },
                        new
                        {
                            Id = 79,
                            Barcode = "0796118461870",
                            CreatedDate = new DateTime(2024, 7, 9, 13, 41, 54, 686, DateTimeKind.Local).AddTicks(2963),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Sleek Wooden Salad",
                            Price = 500.19197839181498
                        },
                        new
                        {
                            Id = 80,
                            Barcode = "5441420559375",
                            CreatedDate = new DateTime(2023, 11, 12, 23, 6, 41, 965, DateTimeKind.Local).AddTicks(1524),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ergonomic Cotton Cheese",
                            Price = 388.41101128254599
                        },
                        new
                        {
                            Id = 81,
                            Barcode = "8127822017206",
                            CreatedDate = new DateTime(2024, 3, 11, 21, 17, 54, 757, DateTimeKind.Local).AddTicks(3457),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Gorgeous Concrete Salad",
                            Price = 790.18422065870107
                        },
                        new
                        {
                            Id = 82,
                            Barcode = "2836556819357",
                            CreatedDate = new DateTime(2024, 3, 12, 8, 17, 36, 290, DateTimeKind.Local).AddTicks(4119),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Gorgeous Wooden Keyboard",
                            Price = 359.85921197657439
                        },
                        new
                        {
                            Id = 83,
                            Barcode = "7852841324400",
                            CreatedDate = new DateTime(2024, 2, 20, 18, 38, 14, 34, DateTimeKind.Local).AddTicks(7415),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Plastic Keyboard",
                            Price = 918.91680194992421
                        },
                        new
                        {
                            Id = 84,
                            Barcode = "9256100365292",
                            CreatedDate = new DateTime(2023, 12, 24, 6, 42, 50, 635, DateTimeKind.Local).AddTicks(5980),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Frozen Mouse",
                            Price = 609.57094184428968
                        },
                        new
                        {
                            Id = 85,
                            Barcode = "4098423130363",
                            CreatedDate = new DateTime(2024, 2, 4, 3, 11, 1, 932, DateTimeKind.Local).AddTicks(476),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Fantastic Plastic Pizza",
                            Price = 346.4543799690224
                        },
                        new
                        {
                            Id = 86,
                            Barcode = "7165157502708",
                            CreatedDate = new DateTime(2023, 12, 30, 12, 56, 41, 182, DateTimeKind.Local).AddTicks(8731),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Incredible Metal Shirt",
                            Price = 219.69463843558665
                        },
                        new
                        {
                            Id = 87,
                            Barcode = "9072296990991",
                            CreatedDate = new DateTime(2024, 6, 17, 2, 8, 59, 439, DateTimeKind.Local).AddTicks(4320),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handmade Cotton Pants",
                            Price = 771.37464212690236
                        },
                        new
                        {
                            Id = 88,
                            Barcode = "8893182042362",
                            CreatedDate = new DateTime(2024, 7, 8, 5, 17, 41, 24, DateTimeKind.Local).AddTicks(7424),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Fantastic Wooden Soap",
                            Price = 168.63343464472959
                        },
                        new
                        {
                            Id = 89,
                            Barcode = "0487815661938",
                            CreatedDate = new DateTime(2023, 10, 18, 5, 55, 19, 666, DateTimeKind.Local).AddTicks(6900),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Rubber Mouse",
                            Price = 383.80313230576138
                        },
                        new
                        {
                            Id = 90,
                            Barcode = "5688025363864",
                            CreatedDate = new DateTime(2024, 5, 12, 22, 13, 15, 409, DateTimeKind.Local).AddTicks(6549),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Rubber Mouse",
                            Price = 487.67439399877298
                        },
                        new
                        {
                            Id = 91,
                            Barcode = "3107752100327",
                            CreatedDate = new DateTime(2024, 8, 15, 12, 47, 32, 211, DateTimeKind.Local).AddTicks(523),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonomic Frozen Chips",
                            Price = 605.73248992056233
                        },
                        new
                        {
                            Id = 92,
                            Barcode = "3146155279780",
                            CreatedDate = new DateTime(2024, 5, 15, 21, 38, 53, 554, DateTimeKind.Local).AddTicks(9417),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Soft Chicken",
                            Price = 572.13452711335128
                        },
                        new
                        {
                            Id = 93,
                            Barcode = "8883591493282",
                            CreatedDate = new DateTime(2023, 11, 8, 19, 9, 49, 824, DateTimeKind.Local).AddTicks(6982),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Tasty Granite Pizza",
                            Price = 835.07818786943244
                        },
                        new
                        {
                            Id = 94,
                            Barcode = "2794257231741",
                            CreatedDate = new DateTime(2023, 12, 28, 16, 51, 35, 358, DateTimeKind.Local).AddTicks(798),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Granite Bike",
                            Price = 669.1514615426546
                        },
                        new
                        {
                            Id = 95,
                            Barcode = "9965575108104",
                            CreatedDate = new DateTime(2024, 5, 10, 23, 18, 28, 920, DateTimeKind.Local).AddTicks(4542),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Concrete Table",
                            Price = 808.69116524545996
                        },
                        new
                        {
                            Id = 96,
                            Barcode = "3352535975696",
                            CreatedDate = new DateTime(2024, 1, 23, 9, 42, 40, 357, DateTimeKind.Local).AddTicks(9320),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Rustic Plastic Computer",
                            Price = 561.68517456282166
                        },
                        new
                        {
                            Id = 97,
                            Barcode = "7711914812858",
                            CreatedDate = new DateTime(2024, 8, 8, 1, 27, 31, 47, DateTimeKind.Local).AddTicks(84),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Practical Fresh Cheese",
                            Price = 239.76816976571837
                        },
                        new
                        {
                            Id = 98,
                            Barcode = "2642950951261",
                            CreatedDate = new DateTime(2024, 7, 12, 11, 42, 10, 788, DateTimeKind.Local).AddTicks(4517),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Generic Metal Car",
                            Price = 59.559374826755082
                        },
                        new
                        {
                            Id = 99,
                            Barcode = "9133862211404",
                            CreatedDate = new DateTime(2024, 7, 3, 6, 32, 29, 603, DateTimeKind.Local).AddTicks(4147),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Generic Fresh Soap",
                            Price = 323.8241613888294
                        },
                        new
                        {
                            Id = 100,
                            Barcode = "2476106364021",
                            CreatedDate = new DateTime(2024, 1, 18, 19, 28, 11, 724, DateTimeKind.Local).AddTicks(6428),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Generic Cotton Table",
                            Price = 508.81764639300189
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
